apiVersion: v2
name: player
description: Player is a window into virtual environments - enabling assignment of
  team membership and customization of responsive, browser-based user interfaces.
type: application
version: 1.8.11
home: https://cmu-sei.github.io/crucible/player
sources:
- https://github.com/cmu-sei/Player.Api
- https://github.com/cmu-sei/Player.Ui
- https://github.com/cmu-sei/Vm.Api
- https://github.com/cmu-sei/Vm.Ui
- https://github.com/cmu-sei/Console.Ui
