apiVersion: v2
name: steamfitter
description: Steamfitter enables the organization and execution of scenario tasks on virtual machines by integrating with StackStorm automation.
type: application
version: 1.6.8
home: https://cmu-sei.github.io/crucible/steamfitter
sources:
  - https://github.com/cmu-sei/steamfitter.api
  - https://github.com/cmu-sei/steamfitter.ui
