apiVersion: v2
name: steamfitter
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.0.0

dependencies:
- name: steamfitter-psql
  version: "0.1.0"
  repository: https://helm.cyberforce.site/charts
- name: steamfitter-api
  version: "0.1.0"
  repository: https://helm.cyberforce.site/charts
- name: steamfitter-ui
  version: "0.1.0"
  repository: https://helm.cyberforce.site/charts