apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}

binaryData:
  signer.pfx: |-
{{ .Values.conf.signer | indent 4 }}

data:
  notice.html: |-
{{ .Values.conf.notice | indent 4 }}
  terms.html: |-
{{ .Values.conf.terms | indent 4 }}
  trouble.html: |-
{{ .Values.conf.trouble | indent 4 }}
  issuers.pem: |-
{{ .Values.conf.issuers | indent 4 }}
  seed.json: |-
{{ .Values.conf.seed | indent 4 }}
