{{- $configMaps := .Values.configMaps | default dict }}
{{- range $name, $configMap := $configMaps }}
{{- if $configMap.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "moodle.fullname" $ }}-{{ $name }}
  labels:
    {{- include "moodle.labels" $ | nindent 4 }}
  {{- with $.Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- toYaml $configMap.data | nindent 2 }}
{{- end }}
{{- end }}

---
{{- $moodle := .Values.moodle | default dict }}
{{- $oidc := $moodle.oidc | default dict }}
{{- if $oidc.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "moodle.fullname" . }}-oidc
  labels:
    {{- include "moodle.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  configure_oidc.sh: {{ .Files.Get "files/configure_oidc.sh" | quote }}
  setup_environment.php: {{ .Files.Get "files/setup_environment.php" | quote }}
{{- end }}
