{{- $ingress := .Values.ingress | default dict }}
{{- if $ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "moodle.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "moodle.labels" . | nindent 4 }}
  {{- $annotations := dict }}
  {{- if .Values.commonAnnotations }}
  {{- $_ := merge $annotations .Values.commonAnnotations }}
  {{- end }}
  {{- if $ingress.annotations }}
  {{- $_ := merge $annotations $ingress.annotations }}
  {{- end }}
  {{- if gt (len $annotations) 0 }}
  annotations:
    {{- range $key, $value := $annotations }}
    {{ $key }}: {{ tpl ($value | toString) $ | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if $ingress.className }}
  ingressClassName: {{ $ingress.className }}
  {{- end }}
  rules:
    - host: {{ tpl ($ingress.hostname | default "moodle.local") . | quote }}
      http:
        paths:
          {{- if $ingress.extraPaths }}
          {{- toYaml $ingress.extraPaths | nindent 10 }}
          {{- end }}
          - path: {{ $ingress.path | default "/" }}
            pathType: {{ $ingress.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "moodle.serviceName" . }}
                port:
                  name: http
    {{- range $ingress.extraHosts }}
    - host: {{ .name | quote }}
      http:
        paths:
          - path: {{ default "/" .path }}
            pathType: {{ default "Prefix" .pathType }}
            backend:
              service:
                name: {{ include "moodle.serviceName" $ }}
                port:
                  name: http
    {{- end }}
    {{- if $ingress.extraRules }}
    {{- toYaml $ingress.extraRules | nindent 4 }}
    {{- end }}
  {{- if $ingress.tls }}
  tls:
    {{- range $ingress.tls }}
    - secretName: {{ .secretName }}
      {{- if .hosts }}
      hosts:
        {{- range .hosts }}
        - {{ tpl . $ | quote }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}