{{- $pdb := .Values.pdb | default dict }}
{{- if $pdb.create }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "moodle.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "moodle.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
spec:
  {{- if $pdb.minAvailable }}
  minAvailable: {{ $pdb.minAvailable }}
  {{- end }}
  {{- if or $pdb.maxUnavailable (not $pdb.minAvailable) }}
  maxUnavailable: {{ $pdb.maxUnavailable | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "moodle.selectorLabels" . | nindent 6 }}
{{- end }}