{{- $moodle := .Values.moodle | default dict }}
{{- $admin := $moodle.admin | default dict }}
{{- if not $admin.existingSecret }}
{{- $secretName := include "moodle.admin.secretName" . }}
{{- $secretKey := $admin.existingSecretKey | default "admin-password" }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- $password := "" }}
{{- if and (hasKey $admin "password") (ne $admin.password "") }}
  {{- $password = $admin.password }}
{{- else if $existingSecret }}
  {{- $password = index $existingSecret.data $secretKey | b64dec }}
{{- else }}
  {{- $password = randAlphaNum 16 }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "moodle.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ $secretKey }}: {{ $password }}
{{- end }}