{{- $moodle := .Values.moodle | default dict }}
{{- $database := $moodle.database | default dict }}
{{- if not $database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "moodle.database.secretName" . }}
  labels:
    {{- include "moodle.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ $database.existingSecretKey | default "postgres-password" }}: {{ required "moodle.database.password is required when existingSecret is not specified" $database.password }}
{{- end }}
