apiVersion: v2
name: moodle
type: application
description: Moodle is an open source Learning Management System.
version: 0.2.4
appVersion: "5.0.1"
home: https://moodle.org/
sources:
  - https://github.com/moodle/moodle
  - https://github.com/erseco/alpine-moodle
